name: CI/CD
on:
  push:
    branches: ["main"]

jobs:
  test-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Download new version of code
        uses: actions/checkout@v4

      - name: Install Golang environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Test new version of code
        run: go test ./...

      - name: Create .env file
        run: |
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "ALLOWED_ORIGIN=${{ secrets.ALLOWED_ORIGIN }}" >> .env

      - name: Deploy new version of code
        run: docker-compose up -d --build
