name: CI/CD
on:
  push:
    branches: ["main"]

jobs:
  test-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Download new version of code
        uses: actions/checkout@v4

      - name: Install Golang environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Test new version of code
        run: go test ./...

      - name: Deploy new version of code
        run: docker-compose up -d --build
